#microservice
server:
    port: 8087

#mongodb
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      authentication-database: admin
      username: ${DB_USER}
      password: ${DB_PASS}
      database: users