#microservice
server:
    port: 8087

spring:
  application:
    name: authuser
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: always
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true

eureka:
  client:
    webclient:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
