#microservice
server:
  port: 8088

api:
  controller:
    path: /authuser-service

spring:
  application:
    name: authuser-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: always
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
#    discovery:
#      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
#  instance:
#    hostname: localhost
