#microservice
server:
    port: 8087
    servlet:
      context-path: /api/v1

#mongodb
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: always

client:
  url: http://localhost:8090/api/v1

